
export const professorCoursesData = {
  'prof-cs101': {
    id: 'prof-cs101',
    name: 'Introduction to Computer Science',
    code: 'CS 101',
    instructor: 'Tamam Alsarhan',
    credits: 3,
    color: 'bg-red-500',
    department: 'King Abdullah II School of Information Technology',
    image: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=500&h=200",
    pastExams: [
      {
        id: 1,
        name: 'Midterm Exam',
        date: '2024-03-15',
        time: '10:00 AM',
        duration: '2 hours',
        location: 'Room A-201',
        type: 'Midterm',
        status: 'completed',
        studentsCount: 45
      },
      {
        id: 2,
        name: 'Programming Assignment Quiz',
        date: '2024-03-22',
        time: '2:00 PM',
        duration: '1 hour',
        location: 'Computer Lab B',
        type: 'Quiz',
        status: 'completed',
        studentsCount: 43
      }
    ]
  },
  'prof-math201': {
    id: 'prof-math201',
    name: 'Calculus II',
    code: 'MATH 201',
    instructor: 'Dr. Sarah Ahmed',
    credits: 4,
    color: 'bg-red-500',
    department: 'King Abdullah II School of Information Technology',
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=500&h=200",
    pastExams: [
      {
        id: 1,
        name: 'Integration Techniques Test',
        date: '2024-03-18',
        time: '11:00 AM',
        duration: '1.5 hours',
        location: 'Room C-105',
        type: 'Test',
        status: 'completed',
        studentsCount: 38
      }
    ]
  }
};

export const examReportsData = {
  1: [ // Midterm Exam
    {
      studentId: '20190123',
      studentName: 'Joud Dababneh',
      cheatingReport: `CHEATING DETECTION REPORT
Generated by Gemini AI - Exam Proctoring System

Student: Joud Dababneh (ID: 20190123)
Exam: Midterm Exam - CS 101
Date: March 15, 2024
Duration: 2 hours

ANALYSIS SUMMARY:
- Total suspicious activities detected: 3
- Confidence level: HIGH

DETECTED BEHAVIORS:
1. [00:23:15] Student looked away from screen for 15 seconds continuously
2. [01:45:30] Multiple people detected in frame for 8 seconds
3. [01:58:42] Potential use of mobile device detected

RECOMMENDATION: Manual review required - Multiple violations detected`,
      decision: null
    },
    {
      studentId: '20190124',
      studentName: 'Fatima Al-Zahra',
      cheatingReport: `CHEATING DETECTION REPORT
Generated by Gemini AI - Exam Proctoring System

Student: Fatima Al-Zahra (ID: 20190124)
Exam: Midterm Exam - CS 101
Date: March 15, 2024
Duration: 2 hours

ANALYSIS SUMMARY:
- Total suspicious activities detected: 0
- Confidence level: HIGH

DETECTED BEHAVIORS:
No suspicious behavior detected during exam session.

RECOMMENDATION: No cheating detected - Clean exam session`,
      decision: null
    },
    {
      studentId: '20190125',
      studentName: 'Omar Mansour',
      cheatingReport: `CHEATING DETECTION REPORT
Generated by Gemini AI - Exam Proctoring System

Student: Omar Mansour (ID: 20190125)
Exam: Midterm Exam - CS 101
Date: March 15, 2024
Duration: 2 hours

ANALYSIS SUMMARY:
- Total suspicious activities detected: 1
- Confidence level: MEDIUM

DETECTED BEHAVIORS:
1. [01:12:45] Extended period looking away from screen (12 seconds)

RECOMMENDATION: Low-risk violation - Likely normal behavior`,
      decision: null
    }
  ],
  2: [ // Programming Assignment Quiz
    {
      studentId: '20190123',
      studentName: 'Joud Dababneh',
      cheatingReport: `CHEATING DETECTION REPORT
Generated by Gemini AI - Exam Proctoring System

Student: Joud Dababneh (ID: 20190123)
Exam: Programming Assignment Quiz - CS 101
Date: March 22, 2024
Duration: 1 hour

ANALYSIS SUMMARY:
- Total suspicious activities detected: 0
- Confidence level: HIGH

DETECTED BEHAVIORS:
No suspicious behavior detected during exam session.

RECOMMENDATION: No cheating detected - Clean exam session`,
      decision: null
    }
  ]
};
